package fiveinrow;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;


public class Startup extends javax.swing.JFrame {
    int level=2;
    
    Music BG;
    String workingDir = System.getProperty("user.dir");
    public Startup() {
        initComponents();
        // Make frame startup position to center
        this.setSize(576, 485);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.BLACK); // Set Background Color
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Black = new javax.swing.JPanel();
        BGMusicVC = new javax.swing.JSlider();
        GP1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BlindSel = new javax.swing.JRadioButton();
        CPUSel = new javax.swing.JRadioButton();
        CPU_SEL = new javax.swing.JLabel();
        LearnerSel = new javax.swing.JRadioButton();
        GExxit = new javax.swing.JLabel();
        SP1 = new javax.swing.JLabel();
        JoinServ = new javax.swing.JLabel();
        CrtServ = new javax.swing.JLabel();
        Exxit = new javax.swing.JLabel();
        SExxit = new javax.swing.JLabel();
        BGIMG = new javax.swing.JLabel();
        SP2 = new javax.swing.JLabel();
        GP2 = new javax.swing.JLabel();
        GCSRV = new javax.swing.JLabel();
        SCSRV = new javax.swing.JLabel();
        GJSRV = new javax.swing.JLabel();
        SJSRV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Five In A Row");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        Black.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(Black);
        Black.setBounds(0, 0, 570, 460);

        BGMusicVC.setMaximum(0);
        BGMusicVC.setMinimum(-20);
        BGMusicVC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BGMusicVCStateChanged(evt);
            }
        });
        BGMusicVC.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BGMusicVCMouseMoved(evt);
            }
        });
        BGMusicVC.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                BGMusicVCPropertyChange(evt);
            }
        });
        getContentPane().add(BGMusicVC);
        BGMusicVC.setBounds(360, 430, 200, 23);

        GP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GP1Btn.png"))); // NOI18N
        GP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GP1MouseClicked(evt);
            }
        });
        getContentPane().add(GP1);
        GP1.setBounds(80, 350, 0, 0);

        P2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P2Btn.png"))); // NOI18N
        P2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P2MouseExited(evt);
            }
        });
        getContentPane().add(P2);
        P2.setBounds(70, 220, 220, 50);

        P1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P1Btn.png"))); // NOI18N
        P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P1MouseExited(evt);
            }
        });
        getContentPane().add(P1);
        P1.setBounds(30, 160, 220, 50);

        jLabel2.setText("Volume");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 420, 80, 14);

        BlindSel.setText("Blind");
        BlindSel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlindSelMouseClicked(evt);
            }
        });
        BlindSel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                BlindSelPropertyChange(evt);
            }
        });
        getContentPane().add(BlindSel);
        BlindSel.setBounds(450, 230, 130, 23);

        CPUSel.setText("CPU :)");
        CPUSel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPUSelMouseClicked(evt);
            }
        });
        getContentPane().add(CPUSel);
        CPUSel.setBounds(450, 270, 130, 23);

        CPU_SEL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CPU_SEL.setText("Difficulty");
        getContentPane().add(CPU_SEL);
        CPU_SEL.setBounds(440, 200, 140, 20);

        LearnerSel.setText("Learner");
        LearnerSel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LearnerSelMouseClicked(evt);
            }
        });
        LearnerSel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                LearnerSelPropertyChange(evt);
            }
        });
        getContentPane().add(LearnerSel);
        LearnerSel.setBounds(450, 250, 130, 23);

        GExxit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GExit.png"))); // NOI18N
        GExxit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GExxitMouseClicked(evt);
            }
        });
        getContentPane().add(GExxit);
        GExxit.setBounds(80, 350, 0, 0);

        SP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P1Btn.png"))); // NOI18N
        SP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SP1MouseClicked(evt);
            }
        });
        getContentPane().add(SP1);
        SP1.setBounds(80, 350, 0, 0);

        JoinServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JSRV.png"))); // NOI18N
        JoinServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JoinServMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JoinServMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JoinServMouseExited(evt);
            }
        });
        getContentPane().add(JoinServ);
        JoinServ.setBounds(290, 340, 220, 50);

        CrtServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CRSRV.png"))); // NOI18N
        CrtServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrtServMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrtServMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrtServMouseExited(evt);
            }
        });
        getContentPane().add(CrtServ);
        CrtServ.setBounds(160, 280, 220, 50);

        Exxit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        Exxit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExxitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExxitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExxitMouseExited(evt);
            }
        });
        getContentPane().add(Exxit);
        Exxit.setBounds(10, 400, 220, 50);

        SExxit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        SExxit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SExxitMouseClicked(evt);
            }
        });
        getContentPane().add(SExxit);
        SExxit.setBounds(80, 350, 0, 0);

        BGIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        getContentPane().add(BGIMG);
        BGIMG.setBounds(0, 0, 570, 465);

        SP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P2Btn.png"))); // NOI18N
        SP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SP2MouseClicked(evt);
            }
        });
        getContentPane().add(SP2);
        SP2.setBounds(80, 350, 0, 0);

        GP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GP2Btn.png"))); // NOI18N
        GP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GP2MouseClicked(evt);
            }
        });
        getContentPane().add(GP2);
        GP2.setBounds(80, 350, 0, 0);

        GCSRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GCRSRV.png"))); // NOI18N
        GCSRV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GCSRVMouseClicked(evt);
            }
        });
        getContentPane().add(GCSRV);
        GCSRV.setBounds(80, 350, 0, 0);

        SCSRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CRSRV.png"))); // NOI18N
        SCSRV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SCSRVMouseClicked(evt);
            }
        });
        getContentPane().add(SCSRV);
        SCSRV.setBounds(80, 350, 0, 0);

        GJSRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GJSRV.png"))); // NOI18N
        GJSRV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GJSRVMouseClicked(evt);
            }
        });
        getContentPane().add(GJSRV);
        GJSRV.setBounds(80, 350, 0, 0);

        SJSRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JSRV.png"))); // NOI18N
        SJSRV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SJSRVMouseClicked(evt);
            }
        });
        getContentPane().add(SJSRV);
        SJSRV.setBounds(80, 350, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Black.setBackground( new Color(0, 0, 0, 0) );
        //BG.volume(0.0f);
         
        workingDir+="\\sounds\\Background.wav";
       
	   System.out.println("Current working directory : " + workingDir);
        
        BG = new Music(workingDir);
        
        BG.play(9999);
        BGMusicVC.setValue(-15);
        BG.volume(BGMusicVC.getValue());
        CPUSel.setSelected(true);

    }//GEN-LAST:event_formWindowActivated

    private void BGMusicVCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BGMusicVCStateChanged
       try{ BG.volume(BGMusicVC.getValue());}catch (Exception e){}
    }//GEN-LAST:event_BGMusicVCStateChanged

    private void BGMusicVCMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMusicVCMouseMoved
        // TODO add your handling code here:
        try{ BG.volume(BGMusicVC.getValue());}catch (Exception e){}
    }//GEN-LAST:event_BGMusicVCMouseMoved

    private void BGMusicVCPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_BGMusicVCPropertyChange
        
    }//GEN-LAST:event_BGMusicVCPropertyChange

    private void P1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseClicked
       
        Game FinRow = new Game(level,BG,false,false,false);
        // Make opening window Location to Center
        
        FinRow.setSize(697, 662);
        FinRow.setLocationRelativeTo(null);
        FinRow.setResizable(false);
        FinRow.show();
        hide();
        enable(false);
    }//GEN-LAST:event_P1MouseClicked

    private void GP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GP1MouseClicked
        
    }//GEN-LAST:event_GP1MouseClicked

    private void SP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SP1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SP1MouseClicked

    private void P1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseEntered
        P1.setIcon(GP1.getIcon());
    }//GEN-LAST:event_P1MouseEntered

    private void P1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseExited
        P1.setIcon(SP1.getIcon());
    }//GEN-LAST:event_P1MouseExited

    private void BlindSelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_BlindSelPropertyChange
       
        
    }//GEN-LAST:event_BlindSelPropertyChange

    private void LearnerSelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_LearnerSelPropertyChange

    }//GEN-LAST:event_LearnerSelPropertyChange

    private void LearnerSelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnerSelMouseClicked
        LearnerSel.setSelected(true);
        BlindSel.setSelected(false);
        CPUSel.setSelected(false);
        level=1;
    }//GEN-LAST:event_LearnerSelMouseClicked

    private void BlindSelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlindSelMouseClicked
        LearnerSel.setSelected(false);
        BlindSel.setSelected(true);
        CPUSel.setSelected(false);
        level=0;
    }//GEN-LAST:event_BlindSelMouseClicked

    private void CPUSelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPUSelMouseClicked
        LearnerSel.setSelected(false);
        BlindSel.setSelected(false);
        CPUSel.setSelected(true);
        level=2;
    }//GEN-LAST:event_CPUSelMouseClicked

    private void ExxitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExxitMouseClicked
        System.exit(0); 
    }//GEN-LAST:event_ExxitMouseClicked

    private void ExxitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExxitMouseEntered
        Exxit.setIcon(GExxit.getIcon());
    }//GEN-LAST:event_ExxitMouseEntered

    private void ExxitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExxitMouseExited
Exxit.setIcon(SExxit.getIcon());
    }//GEN-LAST:event_ExxitMouseExited

    private void GExxitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GExxitMouseClicked
        
    }//GEN-LAST:event_GExxitMouseClicked

    private void SExxitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SExxitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SExxitMouseClicked

    private void CrtServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrtServMouseClicked
         Game FinRow = new Game(-1,BG,true,false,true);
        // Make opening window Location to Center
        
        FinRow.setSize(697, 662);
        FinRow.setLocationRelativeTo(null);
        FinRow.setResizable(false);
        FinRow.show();
        hide();
        enable(false);
    }//GEN-LAST:event_CrtServMouseClicked

    private void CrtServMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrtServMouseEntered
        CrtServ.setIcon(GCSRV.getIcon());
    }//GEN-LAST:event_CrtServMouseEntered

    private void CrtServMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrtServMouseExited
        CrtServ.setIcon(SCSRV.getIcon());
    }//GEN-LAST:event_CrtServMouseExited

    private void SP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SP2MouseClicked

    }//GEN-LAST:event_SP2MouseClicked

    private void GP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GP2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GP2MouseClicked

    private void JoinServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoinServMouseClicked
        Game FinRow = new Game(-1,BG,false,true,true);
        // Make opening window Location to Center
        
        FinRow.setSize(697, 662);
        FinRow.setLocationRelativeTo(null);
        FinRow.setResizable(false);
        FinRow.show();
        hide();
        enable(false);
    }//GEN-LAST:event_JoinServMouseClicked

    private void JoinServMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoinServMouseEntered
        JoinServ.setIcon(GJSRV.getIcon());
    }//GEN-LAST:event_JoinServMouseEntered

    private void JoinServMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoinServMouseExited
        JoinServ.setIcon(SJSRV.getIcon());
    }//GEN-LAST:event_JoinServMouseExited

    private void GCSRVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GCSRVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GCSRVMouseClicked

    private void SCSRVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SCSRVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SCSRVMouseClicked

    private void GJSRVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GJSRVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GJSRVMouseClicked

    private void SJSRVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SJSRVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SJSRVMouseClicked

    private void P2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2MouseClicked
        Game FinRow = new Game(-1,BG,false,false,false);
        // Make opening window Location to Center
        
        FinRow.setSize(697, 662);
        FinRow.setLocationRelativeTo(null);
        FinRow.setResizable(false);
        FinRow.show();
        hide();
        enable(false);
    }//GEN-LAST:event_P2MouseClicked

    private void P2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2MouseEntered
        P2.setIcon(GP2.getIcon());
    }//GEN-LAST:event_P2MouseEntered

    private void P2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2MouseExited
       P2.setIcon(SP2.getIcon());
    }//GEN-LAST:event_P2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGIMG;
    private javax.swing.JSlider BGMusicVC;
    private javax.swing.JPanel Black;
    private javax.swing.JRadioButton BlindSel;
    private javax.swing.JRadioButton CPUSel;
    private javax.swing.JLabel CPU_SEL;
    private javax.swing.JLabel CrtServ;
    private javax.swing.JLabel Exxit;
    private javax.swing.JLabel GCSRV;
    private javax.swing.JLabel GExxit;
    private javax.swing.JLabel GJSRV;
    private javax.swing.JLabel GP1;
    private javax.swing.JLabel GP2;
    private javax.swing.JLabel JoinServ;
    private javax.swing.JRadioButton LearnerSel;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel SCSRV;
    private javax.swing.JLabel SExxit;
    private javax.swing.JLabel SJSRV;
    private javax.swing.JLabel SP1;
    private javax.swing.JLabel SP2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
